"""uodate user table

Revision ID: d28e05d4e8d9
Revises: 8b327ac5e2ff
Create Date: 2022-11-07 17:36:17.902844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28e05d4e8d9'
down_revision = '8b327ac5e2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_birthday'), 'users', ['birthday'], unique=True)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_birthday'), table_name='users')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
