"""empty message

Revision ID: f60aafad459a
Revises: 8bb495f6a0cd
Create Date: 2022-11-09 12:57:15.368406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60aafad459a'
down_revision = '8bb495f6a0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_birthday', table_name='users')
    op.create_index(op.f('ix_users_birthday'), 'users', ['birthday'], unique=False)
    op.drop_index('ix_users_surname', table_name='users')
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.create_index('ix_users_surname', 'users', ['surname'], unique=False)
    op.drop_index(op.f('ix_users_birthday'), table_name='users')
    op.create_index('ix_users_birthday', 'users', ['birthday'], unique=False)
    # ### end Alembic commands ###
